openai_api_key = "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"

[auth]
redirect_uri="http://localhost:8501/oauth2callback"
cookie_secret="b7f8e2c1d4a94e6e8f3a2b1c7e5d4f3a2c1b7e6d4f3a2b1c7e5d4f3a2b1c7e5"

[auth.auth0]
domain="dev-bd4s1emo3v3qus5b.us.auth0.com"
client_id="L31UFzBaODgVP7yIji9VewRBZJnGR5Kb"
client_secret="YPffDufDStms_hiEOMAYU1lJYYzBv_k4k-YwPJL6eEsBen1EdR0fYUAZf8Hzd-2_"
server_metadata_url="https://dev-bd4s1emo3v3qus5b.us.auth0.com/.well-known/openid-configuration"
client_kwargs = {"prompt" = "login"}

[auth.google]
client_id="284782622069-404amigve6rljt34c676sjr40999158f.apps.googleusercontent.com"
client_secret="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"
server_metadata_url="https://accounts.google.com/.well-known/openid-configuration"